weather_forecaster:
  target: local
  outputs:
    local:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', '../data/etl/weather_forecaster.duckdb') }}"
      schema: staging
      threads: 4
    docker:
      type: duckdb
      path: /app/data/etl/weather_forecaster.duckdb
      schema: staging
      threads: 4
