-- Bootstrap script: two-layer RBAC for all four databases.
-- Run once manually as ACCOUNTADMIN after 02_warehouses.sql.
-- Terraform (terraform/modules/rbac/) is the source of truth after bootstrap.
--
-- Layer 1 — Access roles: fine-grained privileges on named objects.
--   Naming: <DB>_DB_READ | <DB>_DB_MODIFY
--           <DB>_<SCHEMA>_READ | _READ_WRITE | _READ_WRITE_CREATE
--
-- Layer 2 — Functional roles: assembled from access roles to match job functions.
--   CSTA_DBT_DEV_ROLE, CSTA_DBT_UAT_ROLE, CSTA_DBT_PROD_ROLE, CSTA_CORTEX_ROLE,
--   CSTA_OBSERVER_ROLE, CSTA_STREAMLIT_ROLE
--
-- Service accounts are mapped to exactly one functional role each.
-- TERRAFORM_SVC is already created with SYSADMIN in 01_databases.sql.

USE ROLE SECURITYADMIN;

-- ===========================================================================
-- SECTION 1 — DB-LEVEL ACCESS ROLES
-- One READ/MODIFY pair per database.
-- READ  → USAGE on the database (required for any object access within it).
-- MODIFY → USAGE + CREATE SCHEMA (dev only: enables per-developer schema namespacing).
-- ===========================================================================

-- CSTA_MARKETING_DEV
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_DB_READ
    COMMENT = 'USAGE on CSTA_MARKETING_DEV database';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_DB_MODIFY
    COMMENT = 'USAGE + CREATE SCHEMA on CSTA_MARKETING_DEV — enables dev schema namespacing';

-- CSTA_MARKETING_UAT
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_DB_READ
    COMMENT = 'USAGE on CSTA_MARKETING_UAT database';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_DB_MODIFY
    COMMENT = 'USAGE + CREATE SCHEMA on CSTA_MARKETING_UAT — reserved for DBA use';

-- CSTA_MARKETING_PROD
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_DB_READ
    COMMENT = 'USAGE on CSTA_MARKETING_PROD database';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_DB_MODIFY
    COMMENT = 'USAGE + CREATE SCHEMA on CSTA_MARKETING_PROD — reserved for DBA use';

-- CSTA_MARKETING_SHARED
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_SHARED_DB_READ
    COMMENT = 'USAGE on CSTA_MARKETING_SHARED database';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_SHARED_DB_MODIFY
    COMMENT = 'USAGE + CREATE SCHEMA on CSTA_MARKETING_SHARED — reserved for DBA use';

-- ===========================================================================
-- SECTION 2 — SCHEMA-LEVEL ACCESS ROLES
-- Three tiers per schema:
--   READ              → USAGE on schema + SELECT on all/future tables and views
--   READ_WRITE        → READ + INSERT/UPDATE/DELETE on all/future tables
--   READ_WRITE_CREATE → READ_WRITE + CREATE TABLE/VIEW/STAGE/PROCEDURE/TASK
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- CSTA_MARKETING_DEV schemas: BRONZE, SILVER, GOLD, ORCHESTRATION
-- ---------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_BRONZE_READ               COMMENT = 'SELECT on CSTA_MARKETING_DEV.BRONZE';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_BRONZE_READ_WRITE         COMMENT = 'SELECT + DML on CSTA_MARKETING_DEV.BRONZE';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE  COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_DEV.BRONZE';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_SILVER_READ               COMMENT = 'SELECT on CSTA_MARKETING_DEV.SILVER';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_SILVER_READ_WRITE         COMMENT = 'SELECT + DML on CSTA_MARKETING_DEV.SILVER';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE  COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_DEV.SILVER';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_GOLD_READ                 COMMENT = 'SELECT on CSTA_MARKETING_DEV.GOLD';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_GOLD_READ_WRITE           COMMENT = 'SELECT + DML on CSTA_MARKETING_DEV.GOLD';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE    COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_DEV.GOLD';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_ORCHESTRATION_READ               COMMENT = 'SELECT on CSTA_MARKETING_DEV.ORCHESTRATION';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE         COMMENT = 'SELECT + DML on CSTA_MARKETING_DEV.ORCHESTRATION';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE  COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_DEV.ORCHESTRATION';

-- ---------------------------------------------------------------------------
-- CSTA_MARKETING_UAT schemas: BRONZE, SILVER, GOLD, ORCHESTRATION
-- ---------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_BRONZE_READ               COMMENT = 'SELECT on CSTA_MARKETING_UAT.BRONZE';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_BRONZE_READ_WRITE         COMMENT = 'SELECT + DML on CSTA_MARKETING_UAT.BRONZE';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE  COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_UAT.BRONZE';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_SILVER_READ               COMMENT = 'SELECT on CSTA_MARKETING_UAT.SILVER';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_SILVER_READ_WRITE         COMMENT = 'SELECT + DML on CSTA_MARKETING_UAT.SILVER';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE  COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_UAT.SILVER';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_GOLD_READ                 COMMENT = 'SELECT on CSTA_MARKETING_UAT.GOLD';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_GOLD_READ_WRITE           COMMENT = 'SELECT + DML on CSTA_MARKETING_UAT.GOLD';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE    COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_UAT.GOLD';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_ORCHESTRATION_READ               COMMENT = 'SELECT on CSTA_MARKETING_UAT.ORCHESTRATION';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE         COMMENT = 'SELECT + DML on CSTA_MARKETING_UAT.ORCHESTRATION';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE  COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_UAT.ORCHESTRATION';

-- ---------------------------------------------------------------------------
-- CSTA_MARKETING_PROD schemas: BRONZE, SILVER, GOLD, ORCHESTRATION
-- ---------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_BRONZE_READ               COMMENT = 'SELECT on CSTA_MARKETING_PROD.BRONZE';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_BRONZE_READ_WRITE         COMMENT = 'SELECT + DML on CSTA_MARKETING_PROD.BRONZE';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE  COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_PROD.BRONZE';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_SILVER_READ               COMMENT = 'SELECT on CSTA_MARKETING_PROD.SILVER';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_SILVER_READ_WRITE         COMMENT = 'SELECT + DML on CSTA_MARKETING_PROD.SILVER';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE  COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_PROD.SILVER';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_GOLD_READ                 COMMENT = 'SELECT on CSTA_MARKETING_PROD.GOLD';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_GOLD_READ_WRITE           COMMENT = 'SELECT + DML on CSTA_MARKETING_PROD.GOLD';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE    COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_PROD.GOLD';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_ORCHESTRATION_READ               COMMENT = 'SELECT on CSTA_MARKETING_PROD.ORCHESTRATION';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE         COMMENT = 'SELECT + DML on CSTA_MARKETING_PROD.ORCHESTRATION';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE  COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_PROD.ORCHESTRATION';

-- ---------------------------------------------------------------------------
-- CSTA_MARKETING_SHARED schemas: OBSERVABILITY, ARTIFACTS
-- ---------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_SHARED_OBSERVABILITY_READ               COMMENT = 'SELECT on CSTA_MARKETING_SHARED.OBSERVABILITY';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE         COMMENT = 'SELECT + DML on CSTA_MARKETING_SHARED.OBSERVABILITY';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE_CREATE  COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_SHARED.OBSERVABILITY';

CREATE ROLE IF NOT EXISTS CSTA_MARKETING_SHARED_ARTIFACTS_READ               COMMENT = 'SELECT on CSTA_MARKETING_SHARED.ARTIFACTS';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE         COMMENT = 'SELECT + DML on CSTA_MARKETING_SHARED.ARTIFACTS';
CREATE ROLE IF NOT EXISTS CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE_CREATE  COMMENT = 'SELECT + DML + DDL on CSTA_MARKETING_SHARED.ARTIFACTS';

-- ===========================================================================
-- SECTION 3 — FUNCTIONAL ROLES
-- Assembled from access roles; match a job function or service identity.
-- ===========================================================================

CREATE ROLE IF NOT EXISTS CSTA_DBT_DEV_ROLE
    COMMENT = 'Full access to CSTA_MARKETING_DEV + shared observability/artefacts; used by SVC_CSTA_DBT_DEV and SVC_GITHUB_CI_DEV';

CREATE ROLE IF NOT EXISTS CSTA_DBT_UAT_ROLE
    COMMENT = 'Full access to CSTA_MARKETING_UAT + shared observability/artefacts; used by SVC_CSTA_DBT_UAT and SVC_GITHUB_CI_UAT';

CREATE ROLE IF NOT EXISTS CSTA_DBT_PROD_ROLE
    COMMENT = 'Full access to CSTA_MARKETING_PROD + shared observability/artefacts; used by SVC_CSTA_DBT_PROD and SVC_GITHUB_CI_PROD';

CREATE ROLE IF NOT EXISTS CSTA_CORTEX_ROLE
    COMMENT = 'Wraps SNOWFLAKE.CORTEX_USER database role; granted to all CSTA_DBT_*_ROLEs';

CREATE ROLE IF NOT EXISTS CSTA_OBSERVER_ROLE
    COMMENT = 'Read-only access to CSTA_MARKETING_SHARED observability + CSTA_MARKETING_PROD gold; for analysts';

CREATE ROLE IF NOT EXISTS CSTA_STREAMLIT_ROLE
    COMMENT = 'Service identity for the Observability Streamlit app; inherits CSTA_OBSERVER_ROLE';

CREATE ROLE IF NOT EXISTS CSTA_ANALYST_ROLE
    COMMENT = 'Read-only access to UAT and PROD GOLD schemas only; for business analysts querying mart tables — no bronze, silver, or observability';

CREATE ROLE IF NOT EXISTS CSTA_DEV_ROLE
    COMMENT = 'Full read/write/create on all DEV database objects; assigned to named human developers, not service accounts';

CREATE ROLE IF NOT EXISTS CSTA_UAT_DEV_ROLE
    COMMENT = 'Full read/write/create on all UAT database objects; assigned to named human developers and QA engineers, not service accounts';

-- ===========================================================================
-- SECTION 4 — PRIVILEGE GRANTS TO ACCESS ROLES
-- ===========================================================================

USE ROLE SYSADMIN;

-- ---------------------------------------------------------------------------
-- DB-level: CSTA_MARKETING_DEV
-- ---------------------------------------------------------------------------
GRANT USAGE ON DATABASE CSTA_MARKETING_DEV TO ROLE CSTA_MARKETING_DEV_DB_READ;

GRANT USAGE         ON DATABASE CSTA_MARKETING_DEV TO ROLE CSTA_MARKETING_DEV_DB_MODIFY;
GRANT CREATE SCHEMA ON DATABASE CSTA_MARKETING_DEV TO ROLE CSTA_MARKETING_DEV_DB_MODIFY;

-- ---------------------------------------------------------------------------
-- DB-level: CSTA_MARKETING_UAT
-- ---------------------------------------------------------------------------
GRANT USAGE ON DATABASE CSTA_MARKETING_UAT TO ROLE CSTA_MARKETING_UAT_DB_READ;

GRANT USAGE         ON DATABASE CSTA_MARKETING_UAT TO ROLE CSTA_MARKETING_UAT_DB_MODIFY;
GRANT CREATE SCHEMA ON DATABASE CSTA_MARKETING_UAT TO ROLE CSTA_MARKETING_UAT_DB_MODIFY;

-- ---------------------------------------------------------------------------
-- DB-level: CSTA_MARKETING_PROD
-- ---------------------------------------------------------------------------
GRANT USAGE ON DATABASE CSTA_MARKETING_PROD TO ROLE CSTA_MARKETING_PROD_DB_READ;

GRANT USAGE         ON DATABASE CSTA_MARKETING_PROD TO ROLE CSTA_MARKETING_PROD_DB_MODIFY;
GRANT CREATE SCHEMA ON DATABASE CSTA_MARKETING_PROD TO ROLE CSTA_MARKETING_PROD_DB_MODIFY;

-- ---------------------------------------------------------------------------
-- DB-level: CSTA_MARKETING_SHARED
-- ---------------------------------------------------------------------------
GRANT USAGE ON DATABASE CSTA_MARKETING_SHARED TO ROLE CSTA_MARKETING_SHARED_DB_READ;

GRANT USAGE         ON DATABASE CSTA_MARKETING_SHARED TO ROLE CSTA_MARKETING_SHARED_DB_MODIFY;
GRANT CREATE SCHEMA ON DATABASE CSTA_MARKETING_SHARED TO ROLE CSTA_MARKETING_SHARED_DB_MODIFY;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_DEV.BRONZE
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_DEV.BRONZE TO ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_DEV.SILVER
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_DEV.SILVER TO ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_DEV.GOLD
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_DEV.GOLD TO ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_DEV.ORCHESTRATION
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_DEV.ORCHESTRATION TO ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_UAT.BRONZE
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_UAT.BRONZE TO ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_UAT.SILVER
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_UAT.SILVER TO ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_UAT.GOLD
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_UAT.GOLD TO ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_UAT.ORCHESTRATION
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_UAT.ORCHESTRATION TO ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_PROD.BRONZE
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_PROD.BRONZE TO ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_PROD.SILVER
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_PROD.SILVER TO ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_PROD.GOLD
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_PROD.GOLD TO ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_PROD.ORCHESTRATION
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_PROD.ORCHESTRATION TO ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_SHARED.OBSERVABILITY
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_SHARED.OBSERVABILITY TO ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE_CREATE;

-- ---------------------------------------------------------------------------
-- Schema-level: CSTA_MARKETING_SHARED.ARTIFACTS
-- ---------------------------------------------------------------------------
GRANT USAGE                        ON SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ;
GRANT SELECT ON ALL TABLES         IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ;
GRANT SELECT ON FUTURE TABLES      IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ;
GRANT SELECT ON ALL VIEWS          IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ;
GRANT SELECT ON FUTURE VIEWS       IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE;

GRANT USAGE                                    ON SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE_CREATE;
GRANT SELECT ON ALL TABLES                     IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE TABLES                  IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE_CREATE;
GRANT SELECT ON ALL VIEWS                      IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE_CREATE;
GRANT SELECT ON FUTURE VIEWS                   IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES     IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE_CREATE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES  IN SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE_CREATE;
GRANT CREATE TABLE     ON SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE_CREATE;
GRANT CREATE VIEW      ON SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE_CREATE;
GRANT CREATE STAGE     ON SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE_CREATE;
GRANT CREATE PROCEDURE ON SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE_CREATE;
GRANT CREATE TASK      ON SCHEMA CSTA_MARKETING_SHARED.ARTIFACTS TO ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE_CREATE;

-- ===========================================================================
-- SECTION 5 — ASSEMBLE FUNCTIONAL ROLES FROM ACCESS ROLES
-- ===========================================================================

USE ROLE SECURITYADMIN;

-- ---------------------------------------------------------------------------
-- CSTA_DBT_DEV_ROLE
--   Full write+create on all dev schemas.
--   DB_MODIFY (not READ) enables per-developer schema namespacing via
--   macros/generate_schema_name.sql → CSTA_DBT_<user>_<layer>.
-- ---------------------------------------------------------------------------
GRANT ROLE CSTA_MARKETING_DEV_DB_MODIFY                        TO ROLE CSTA_DBT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE         TO ROLE CSTA_DBT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE         TO ROLE CSTA_DBT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE           TO ROLE CSTA_DBT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE  TO ROLE CSTA_DBT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_DB_READ                       TO ROLE CSTA_DBT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE      TO ROLE CSTA_DBT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE          TO ROLE CSTA_DBT_DEV_ROLE;

-- ---------------------------------------------------------------------------
-- CSTA_DBT_UAT_ROLE
--   Full write+create on all uat schemas.
--   DB_READ (not MODIFY) — schema namespacing is not used in UAT.
-- ---------------------------------------------------------------------------
GRANT ROLE CSTA_MARKETING_UAT_DB_READ                          TO ROLE CSTA_DBT_UAT_ROLE;
GRANT ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE         TO ROLE CSTA_DBT_UAT_ROLE;
GRANT ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE         TO ROLE CSTA_DBT_UAT_ROLE;
GRANT ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE           TO ROLE CSTA_DBT_UAT_ROLE;
GRANT ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE  TO ROLE CSTA_DBT_UAT_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_DB_READ                       TO ROLE CSTA_DBT_UAT_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE      TO ROLE CSTA_DBT_UAT_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE          TO ROLE CSTA_DBT_UAT_ROLE;

-- ---------------------------------------------------------------------------
-- CSTA_DBT_PROD_ROLE
--   Full write+create on all prod schemas.
-- ---------------------------------------------------------------------------
GRANT ROLE CSTA_MARKETING_PROD_DB_READ                          TO ROLE CSTA_DBT_PROD_ROLE;
GRANT ROLE CSTA_MARKETING_PROD_BRONZE_READ_WRITE_CREATE         TO ROLE CSTA_DBT_PROD_ROLE;
GRANT ROLE CSTA_MARKETING_PROD_SILVER_READ_WRITE_CREATE         TO ROLE CSTA_DBT_PROD_ROLE;
GRANT ROLE CSTA_MARKETING_PROD_GOLD_READ_WRITE_CREATE           TO ROLE CSTA_DBT_PROD_ROLE;
GRANT ROLE CSTA_MARKETING_PROD_ORCHESTRATION_READ_WRITE_CREATE  TO ROLE CSTA_DBT_PROD_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_DB_READ                        TO ROLE CSTA_DBT_PROD_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE       TO ROLE CSTA_DBT_PROD_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE           TO ROLE CSTA_DBT_PROD_ROLE;

-- ---------------------------------------------------------------------------
-- CSTA_OBSERVER_ROLE
--   Read-only access for analysts and the Streamlit app.
--   Uses CSTA_DBT_DEV_WH — not prod — to avoid contention with the pipeline.
-- ---------------------------------------------------------------------------
GRANT ROLE CSTA_MARKETING_SHARED_DB_READ             TO ROLE CSTA_OBSERVER_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ  TO ROLE CSTA_OBSERVER_ROLE;
GRANT ROLE CSTA_MARKETING_PROD_DB_READ               TO ROLE CSTA_OBSERVER_ROLE;
GRANT ROLE CSTA_MARKETING_PROD_GOLD_READ             TO ROLE CSTA_OBSERVER_ROLE;

-- ---------------------------------------------------------------------------
-- CSTA_STREAMLIT_ROLE
--   Inherits CSTA_OBSERVER_ROLE and adds the Streamlit network integration.
--   The integration must exist before this grant takes effect; see
--   04_stages.sql for CSTA_STREAMLIT_INTEGRATION creation.
-- ---------------------------------------------------------------------------
GRANT ROLE CSTA_OBSERVER_ROLE TO ROLE CSTA_STREAMLIT_ROLE;

-- ---------------------------------------------------------------------------
-- CSTA_CORTEX_ROLE
--   Wraps the SNOWFLAKE.CORTEX_USER database role so that any functional
--   role granted CSTA_CORTEX_ROLE can invoke Cortex functions (TRANSLATE,
--   AI_SENTIMENT, COMPLETE, FORECAST).
-- ---------------------------------------------------------------------------
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CSTA_CORTEX_ROLE;

GRANT ROLE CSTA_CORTEX_ROLE TO ROLE CSTA_DBT_DEV_ROLE;
GRANT ROLE CSTA_CORTEX_ROLE TO ROLE CSTA_DBT_UAT_ROLE;
GRANT ROLE CSTA_CORTEX_ROLE TO ROLE CSTA_DBT_PROD_ROLE;

-- ---------------------------------------------------------------------------
-- Warehouse usage grants
-- ---------------------------------------------------------------------------
USE ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE CSTA_DBT_DEV_WH  TO ROLE CSTA_DBT_DEV_ROLE;
GRANT USAGE ON WAREHOUSE CSTA_DBT_UAT_WH  TO ROLE CSTA_DBT_UAT_ROLE;
GRANT USAGE ON WAREHOUSE CSTA_DBT_PROD_WH TO ROLE CSTA_DBT_PROD_ROLE;
-- Analysts query via dev WH to avoid contention with the prod pipeline.
GRANT USAGE ON WAREHOUSE CSTA_DBT_DEV_WH  TO ROLE CSTA_OBSERVER_ROLE;

-- ---------------------------------------------------------------------------
-- EXECUTE TASK privilege — scoped to dev task ownership only for CSTA_DBT_DEV_ROLE.
-- CSTA_DBT_UAT_ROLE and CSTA_DBT_PROD_ROLE inherit EXECUTE TASK via task ownership
-- (the service account that creates the task can execute it without this grant).
-- ---------------------------------------------------------------------------
GRANT EXECUTE TASK ON ACCOUNT TO ROLE CSTA_DBT_DEV_ROLE;

-- ===========================================================================
-- SECTION 7 — HUMAN USER FUNCTIONAL ROLES
-- ===========================================================================

USE ROLE SECURITYADMIN;

-- ---------------------------------------------------------------------------
-- CSTA_ANALYST_ROLE — gold read-only on UAT and PROD
-- ---------------------------------------------------------------------------
GRANT ROLE CSTA_MARKETING_UAT_DB_READ    TO ROLE CSTA_ANALYST_ROLE;
GRANT ROLE CSTA_MARKETING_UAT_GOLD_READ  TO ROLE CSTA_ANALYST_ROLE;
GRANT ROLE CSTA_MARKETING_PROD_DB_READ   TO ROLE CSTA_ANALYST_ROLE;
GRANT ROLE CSTA_MARKETING_PROD_GOLD_READ TO ROLE CSTA_ANALYST_ROLE;

USE ROLE SYSADMIN;

-- Analysts use dev WH to avoid contention with the prod pipeline.
GRANT USAGE ON WAREHOUSE CSTA_DBT_DEV_WH TO ROLE CSTA_ANALYST_ROLE;

USE ROLE SECURITYADMIN;

-- ---------------------------------------------------------------------------
-- CSTA_DEV_ROLE — full DEV access for human developers
-- ---------------------------------------------------------------------------
GRANT ROLE CSTA_MARKETING_DEV_DB_MODIFY                        TO ROLE CSTA_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_DEV_BRONZE_READ_WRITE_CREATE         TO ROLE CSTA_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_DEV_SILVER_READ_WRITE_CREATE         TO ROLE CSTA_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_DEV_GOLD_READ_WRITE_CREATE           TO ROLE CSTA_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_DEV_ORCHESTRATION_READ_WRITE_CREATE  TO ROLE CSTA_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_DB_READ                       TO ROLE CSTA_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE      TO ROLE CSTA_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE          TO ROLE CSTA_DEV_ROLE;
GRANT ROLE CSTA_CORTEX_ROLE                                    TO ROLE CSTA_DEV_ROLE;

USE ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE CSTA_DBT_DEV_WH TO ROLE CSTA_DEV_ROLE;
GRANT EXECUTE TASK ON ACCOUNT             TO ROLE CSTA_DEV_ROLE;

USE ROLE SECURITYADMIN;

-- ---------------------------------------------------------------------------
-- CSTA_UAT_DEV_ROLE — full UAT access for developers and QA engineers
-- ---------------------------------------------------------------------------
GRANT ROLE CSTA_MARKETING_UAT_DB_READ                          TO ROLE CSTA_UAT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_UAT_BRONZE_READ_WRITE_CREATE         TO ROLE CSTA_UAT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_UAT_SILVER_READ_WRITE_CREATE         TO ROLE CSTA_UAT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_UAT_GOLD_READ_WRITE_CREATE           TO ROLE CSTA_UAT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_UAT_ORCHESTRATION_READ_WRITE_CREATE  TO ROLE CSTA_UAT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_DB_READ                       TO ROLE CSTA_UAT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_OBSERVABILITY_READ_WRITE      TO ROLE CSTA_UAT_DEV_ROLE;
GRANT ROLE CSTA_MARKETING_SHARED_ARTIFACTS_READ_WRITE          TO ROLE CSTA_UAT_DEV_ROLE;
GRANT ROLE CSTA_CORTEX_ROLE                                    TO ROLE CSTA_UAT_DEV_ROLE;

USE ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE CSTA_DBT_UAT_WH TO ROLE CSTA_UAT_DEV_ROLE;

-- ---------------------------------------------------------------------------
-- Streamlit network integration
--   Allows the Streamlit app hosted in Snowflake to serve external traffic.
--   Adjust ALLOWED_URLS if you restrict to a custom domain.
-- ---------------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;

CREATE NETWORK RULE IF NOT EXISTS CSTA_MARKETING_SHARED.ARTIFACTS.CSTA_STREAMLIT_NETWORK_RULE
    TYPE        = HOST_PORT
    VALUE_LIST  = ('0.0.0.0/0:443')
    MODE        = EGRESS
    COMMENT     = 'Allow outbound HTTPS from Streamlit app';

CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS CSTA_STREAMLIT_INTEGRATION
    ALLOWED_NETWORK_RULES = (CSTA_MARKETING_SHARED.ARTIFACTS.CSTA_STREAMLIT_NETWORK_RULE)
    ENABLED               = TRUE
    COMMENT               = 'Network integration for Observability Streamlit app';

USE ROLE SECURITYADMIN;

GRANT USAGE ON INTEGRATION CSTA_STREAMLIT_INTEGRATION TO ROLE CSTA_STREAMLIT_ROLE;

-- ---------------------------------------------------------------------------
-- Anchor all functional roles under SYSADMIN in the role hierarchy.
-- ---------------------------------------------------------------------------
GRANT ROLE CSTA_DBT_DEV_ROLE    TO ROLE SYSADMIN;
GRANT ROLE CSTA_DBT_UAT_ROLE    TO ROLE SYSADMIN;
GRANT ROLE CSTA_DBT_PROD_ROLE   TO ROLE SYSADMIN;
GRANT ROLE CSTA_CORTEX_ROLE     TO ROLE SYSADMIN;
GRANT ROLE CSTA_OBSERVER_ROLE   TO ROLE SYSADMIN;
GRANT ROLE CSTA_STREAMLIT_ROLE  TO ROLE SYSADMIN;
GRANT ROLE CSTA_ANALYST_ROLE    TO ROLE SYSADMIN;
GRANT ROLE CSTA_DEV_ROLE        TO ROLE SYSADMIN;
GRANT ROLE CSTA_UAT_DEV_ROLE    TO ROLE SYSADMIN;

-- ===========================================================================
-- SECTION 6 — SERVICE ACCOUNT USERS AND ROLE MAPPINGS
--
-- Each service account authenticates via key-pair only (no password).
-- Replace each <RSA_PUBLIC_KEY_*> placeholder with the base64 body of the
-- corresponding .pub file before running this script.
-- ===========================================================================

USE ROLE ACCOUNTADMIN;

CREATE USER IF NOT EXISTS SVC_CSTA_DBT_DEV
    RSA_PUBLIC_KEY       = '<RSA_PUBLIC_KEY_SVC_CSTA_DBT_DEV>'
    DEFAULT_ROLE         = CSTA_DBT_DEV_ROLE
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT              = 'dbt dev service account — used by developers and SVC_GITHUB_CI_DEV';

CREATE USER IF NOT EXISTS SVC_CSTA_DBT_UAT
    RSA_PUBLIC_KEY       = '<RSA_PUBLIC_KEY_SVC_CSTA_DBT_UAT>'
    DEFAULT_ROLE         = CSTA_DBT_UAT_ROLE
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT              = 'dbt UAT service account — used by ci_uat.yml and uat Task DAG';

CREATE USER IF NOT EXISTS SVC_CSTA_DBT_PROD
    RSA_PUBLIC_KEY       = '<RSA_PUBLIC_KEY_SVC_CSTA_DBT_PROD>'
    DEFAULT_ROLE         = CSTA_DBT_PROD_ROLE
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT              = 'dbt prod service account — used by ci_prod.yml and prod Task DAG';

CREATE USER IF NOT EXISTS SVC_STREAMLIT
    RSA_PUBLIC_KEY       = '<RSA_PUBLIC_KEY_SVC_STREAMLIT>'
    DEFAULT_ROLE         = CSTA_STREAMLIT_ROLE
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT              = 'Observability Streamlit app service account';

-- One GitHub Actions service account per environment so that CI secrets are
-- scoped and a dev credential leak cannot affect prod.
CREATE USER IF NOT EXISTS SVC_GITHUB_CI_DEV
    RSA_PUBLIC_KEY       = '<RSA_PUBLIC_KEY_SVC_GITHUB_CI_DEV>'
    DEFAULT_ROLE         = CSTA_DBT_DEV_ROLE
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT              = 'GitHub Actions CI service account for dev environment (ci_dev.yml)';

CREATE USER IF NOT EXISTS SVC_GITHUB_CI_UAT
    RSA_PUBLIC_KEY       = '<RSA_PUBLIC_KEY_SVC_GITHUB_CI_UAT>'
    DEFAULT_ROLE         = CSTA_DBT_UAT_ROLE
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT              = 'GitHub Actions CI service account for UAT environment (ci_uat.yml)';

CREATE USER IF NOT EXISTS SVC_GITHUB_CI_PROD
    RSA_PUBLIC_KEY       = '<RSA_PUBLIC_KEY_SVC_GITHUB_CI_PROD>'
    DEFAULT_ROLE         = CSTA_DBT_PROD_ROLE
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT              = 'GitHub Actions CI service account for prod environment (ci_prod.yml)';

USE ROLE SECURITYADMIN;

GRANT ROLE CSTA_DBT_DEV_ROLE   TO USER SVC_CSTA_DBT_DEV;
GRANT ROLE CSTA_DBT_UAT_ROLE   TO USER SVC_CSTA_DBT_UAT;
GRANT ROLE CSTA_DBT_PROD_ROLE  TO USER SVC_CSTA_DBT_PROD;
GRANT ROLE CSTA_STREAMLIT_ROLE TO USER SVC_STREAMLIT;

GRANT ROLE CSTA_DBT_DEV_ROLE   TO USER SVC_GITHUB_CI_DEV;
GRANT ROLE CSTA_DBT_UAT_ROLE   TO USER SVC_GITHUB_CI_UAT;
GRANT ROLE CSTA_DBT_PROD_ROLE  TO USER SVC_GITHUB_CI_PROD;
